# Generated by Django 2.2.28 on 2023-09-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_enemy', to='home.Dog')),
            ],
        ),
    ]
