# Generated by Django 2.2.28 on 2023-09-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_enemy', to='home.Cat'),
        ),
    ]
