# Generated by Django 2.2.28 on 2023-09-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_testmodel_testmodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='r1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testmodel_r1', to='home.TestModel3'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='r2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testmodel_r2', to='home.TestModel4'),
        ),
    ]
